server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1