### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with Kafka",
  "email": "kafka_test31@example.com",
  "address": "123 street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###