### Creates a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe with Kafka",
  "email": "kafka_test31@example.com",
  "address": "123 street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###